# Workflow for building and publishing data contracts in Python

name: Docker Image Size diff "latest"

on: pull_request

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      id-token: write
      contents: write
    steps:
      - name: Inspect event payload
        run: cat ${{ github.event_path }}

      - name: Checkout base
        uses: actions/checkout@v2
        with:
          ref: ${{ github.base_ref }}
          path: base/

      - name: Checkout head
        uses: actions/checkout@v3
        with:
          # Note that this is a default 'ref', adding for readability.
          ref: ${{ github.sha }}
          path: head/

      - name: Install prerequisited
        run:
          # From https://github.com/wagoodman/dive#installation
          wget https://github.com/wagoodman/dive/releases/download/v0.9.2/dive_0.9.2_linux_amd64.deb
          sudo apt install ./dive_0.9.2_linux_amd64.deb
          dive --version
          jq --version

      - name: Transform base
        working-directory: base/
        run: |
          echo base
        
      - name: Transform test
        working-directory: test/
        run: |
          echo test
        
